name: Run Python tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: pwd
        run: pwd
      - name: ls
        run: pwd
      - name: install deps
        run: pip install -e .
        
